databases:
  - name: inventory_qr_db
    plan: free
    databaseName:  inventory_qr_db
    user:  inventory_qr_db

services:
  - type: web
    plan: free
    name: inventory_qr
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn container_qr.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory_qr_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4